### ISSUE TITLE
 cannot find -lcgco: No such file or directory

### ISSUE THREAD

**Issue by T0nyWei** [Borda/pyGCO#25] opened 2022-10-16 14:15 UTC
Hi! I was trying to compile the wrappers of your library. Other parts in the Makefile worked fine, but when I tried to run
 `make test_wrapper`
I got the following error message. 
```
g++ -Igco_source -Igco -L. test_wrapper.cpp \
    -o test_wrapper -Wl,-rpath,. -lcgco
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcgco: No such file or directory
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:61: test_wrapper] Error 1
```

I'm sorry that I am new to compiling wrappers and any help would be greatly appreciated! Thanks in advance!

**Comment by Borda** [comment] 2022-10-17 08:44
Hi, @T0nyWei have you run the whole sequence of commands?
Also, why not install the package from PyPI? https://pypi.org/project/gco-wrapper/

**Comment by T0nyWei** [comment] 2022-10-17 09:48
Hello, @Borda thanks for the reply! 
I found that the download link in the Makefile was not the latest, but I've managed to download the codes and extracted them to gco_source. However, `make all` and `make test_wrapper` were giving me the same error message. 
Besides, I've installed the package from PyPI and was able to do `import gco` in python files. However, the test_examples.py is still giving error messages saying no modules named pygco and cgco. Is that normal and could I use the gco package directly? Thanks again!

**Comment by Borda** [comment] 2022-11-07 08:35
can you pls share what URL have you used for downloading the code?

**Comment by T0nyWei** [comment] 2022-11-07 08:47
For the gco-v3.0 I downloaded from https://vision.cs.uwaterloo.ca/files/gco-v3.0.zip. 
BTW I just tried to run the `make` commands without downloading and replacing the codes and it completed with no errors but just some warning messages. Perhaps it was caused by the fact that there were some updates to the GCO source codes? 
Thank you again for the reply!

**Comment by Borda** [comment] 2022-11-07 11:05
Yes, sounds like that, as they provide it as an archive only without any change history, and the version was not bumped (this python wrapper was built for 3.0, and they share theirs as 3.0 too)
@T0nyWei, would you be interested in checking with the authors what the changes were and how much important they were, like if they fixed some bugs or if it was just a cosmetical update...?

**Comment by T0nyWei** [comment] 2022-11-07 12:46
I'd like to but I'm afraid that my knowledge in this area is not adequate... :( My major is not in this direction and I am just trying to finish one of my class assignments. I'm also not familiar with the authors. Sorry that I cannot help and great thanks again for your effort and help!

**Comment by 1022WANG** [comment] 2023-06-11 07:12
I have the same problem. Have you fixed them?

**Comment by Borda** [comment] 2023-06-12 12:05
hi, could you pls try to install from source:
```
pip install https://github.com/Borda/pyGCO/archive/refs/heads/master.zip

**Comment by Borda** [comment] 2023-06-12 12:09
Closing as it works for me and missing reproducible example... :flamingo: 
feel free to reopen if need :)

**Closed by Borda** 2023-06-12 12:09 UTC
Labels: bug, help wanted
